# Generated by Django 4.2.7 on 2025-11-03 15:04

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [("maps", "0001_initial")]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_airport_geom "
            "ON maps_airport USING GIST (geom);"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_flightroute_geom "
            "ON maps_flightroute USING GIST (geom);"
        ),
    ]
