"""
Django settings for CA project.

Generated by 'django-admin startproject' using Django 4.2.7.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# =========================
# CORE SECURITY / ENV SETUP
# =========================

# SECRET_KEY: use env in Docker/prod, default for local dev
SECRET_KEY = os.environ.get("SECRET_KEY", "your-secret-key-here")

# DEBUG: True by default for local dev
DEBUG = os.environ.get("DEBUG", "True") == "True"

# ALLOWED_HOSTS: comma-separated in env, fallback for local
ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

# =========================
# GDAL / GEOS / PROJ
# =========================

# On Windows (local dev), use your installed GDAL paths
if os.name == "nt":
    GDAL_LIBRARY_PATH = r"C:\Program Files\GDAL\bin\gdal.dll"
    GEOS_LIBRARY_PATH = r"C:\Program Files\GDAL\bin\geos_c.dll"
    PROJ_LIBRARY_PATH = r"C:\Program Files\GDAL\bin\proj_9.dll"
else:
    # In Docker, these are provided by the Dockerfile as env vars
    GDAL_LIBRARY_PATH = os.environ.get("GDAL_LIBRARY_PATH")
    GEOS_LIBRARY_PATH = os.environ.get("GEOS_LIBRARY_PATH")
    PROJ_LIBRARY_PATH = os.environ.get("PROJ_LIBRARY_PATH")

# =========================
# APPLICATION DEFINITION
# =========================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # GeoDjango
    'django.contrib.gis',

    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Local apps
    'maps',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CA.wsgi.application'

# =========================
# DATABASE (LOCAL + DOCKER)
# =========================
# Defaults match your existing local setup:
#   host=localhost, port=5433
# Docker overrides these via environment variables in docker-compose.yml

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('DATABASE_NAME', 'webmapping_db_ca'),
        'USER': os.environ.get('DATABASE_USER', 'webmappingca'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'awm123'),
        'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
        'PORT': os.environ.get('DATABASE_PORT', '5433'),
    }
}

# =========================
# INTERNATIONALIZATION
# =========================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# =========================
# STATIC & MEDIA FILES
# =========================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =========================
# DEFAULT PRIMARY KEY FIELD
# =========================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =========================
# REST FRAMEWORK
# =========================

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# =========================
# CORS
# =========================

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
